export const ERROR_CATEGORIES = {
  VALIDATION: 'VALIDATION',
  AUTH: 'AUTH',
  PERMISSION: 'PERMISSION',
  NOT_FOUND: 'NOT_FOUND',
  NETWORK: 'NETWORK',
  SERVER: 'SERVER',
  BUSINESS: 'BUSINESS',
} as const;

export type ErrorCategory = (typeof ERROR_CATEGORIES)[keyof typeof ERROR_CATEGORIES];

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  WRONG_PORTAL: 'WRONG_PORTAL',
  APPROVAL_PENDING: 'APPROVAL_PENDING',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  ACCOUNT_NO_PASSWORD: 'ACCOUNT_NO_PASSWORD',
  ACCOUNT_INVITED_ONLY: 'ACCOUNT_INVITED_ONLY',
  ACCOUNT_PENDING: 'ACCOUNT_PENDING',
  USER_SUSPENDED: 'USER_SUSPENDED',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  INVITE_TOKEN_EXPIRED: 'INVITE_TOKEN_EXPIRED',
  INVITE_TOKEN_USED: 'INVITE_TOKEN_USED',
  INVITE_TOKEN_INVALID: 'INVITE_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  RESET_TOKEN_USED: 'RESET_TOKEN_USED',
  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  JOB_NOT_OPEN: 'JOB_NOT_OPEN',
  JOB_IS_CLOSED: 'JOB_IS_CLOSED',
  INVALID_STAGE_TRANSITION: 'INVALID_STAGE_TRANSITION',
  ALREADY_IN_PIPELINE: 'ALREADY_IN_PIPELINE',
  NO_RESUME: 'NO_RESUME',
  NO_SKILL_WEIGHTS: 'NO_SKILL_WEIGHTS',
  AI_EVALUATION_FAILED: 'AI_EVALUATION_FAILED',
  AI_PAYMENT_REQUIRED: 'AI_PAYMENT_REQUIRED',
  STORAGE_ERROR: 'STORAGE_ERROR',
  EMAIL_FAILED: 'EMAIL_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  LINKEDIN_NOT_CONNECTED: 'LINKEDIN_NOT_CONNECTED',
  LINKEDIN_TOKEN_EXPIRED: 'LINKEDIN_TOKEN_EXPIRED',
  LINKEDIN_POST_FAILED: 'LINKEDIN_POST_FAILED',
  LINKEDIN_ORG_NOT_FOUND: 'LINKEDIN_ORG_NOT_FOUND',
  LINKEDIN_RATE_LIMITED: 'LINKEDIN_RATE_LIMITED',
  LINKEDIN_DUPLICATE_POST: 'LINKEDIN_DUPLICATE_POST',
  LINKEDIN_SCOPE_DENIED: 'LINKEDIN_SCOPE_DENIED',
  LINKEDIN_OAUTH_FAILED: 'LINKEDIN_OAUTH_FAILED',
  LINKEDIN_NETWORK_ERROR: 'LINKEDIN_NETWORK_ERROR',
} as const;

const VALIDATION_CODES = new Set<string>([
  ERROR_CODES.VALIDATION_ERROR,
  ERROR_CODES.OTP_EXPIRED,
  ERROR_CODES.OTP_INVALID,
  ERROR_CODES.OTP_MAX_ATTEMPTS,
  ERROR_CODES.OTP_RATE_LIMITED,
]);

const AUTH_CODES = new Set<string>([
  ERROR_CODES.UNAUTHORIZED,
  ERROR_CODES.EMAIL_NOT_FOUND,
  ERROR_CODES.INVALID_TOKEN,
  ERROR_CODES.TOKEN_EXPIRED,
  ERROR_CODES.SESSION_EXPIRED,
  ERROR_CODES.WRONG_PORTAL,
  ERROR_CODES.APPROVAL_PENDING,
  ERROR_CODES.APPROVAL_REJECTED,
  ERROR_CODES.ACCOUNT_NO_PASSWORD,
  ERROR_CODES.ACCOUNT_INVITED_ONLY,
  ERROR_CODES.ACCOUNT_PENDING,
  ERROR_CODES.INVITE_TOKEN_EXPIRED,
  ERROR_CODES.INVITE_TOKEN_USED,
  ERROR_CODES.INVITE_TOKEN_INVALID,
  ERROR_CODES.RESET_TOKEN_EXPIRED,
  ERROR_CODES.RESET_TOKEN_USED,
  ERROR_CODES.RESET_TOKEN_INVALID,
]);

const PERMISSION_CODES = new Set<string>([
  ERROR_CODES.FORBIDDEN,
  ERROR_CODES.USER_SUSPENDED,
  ERROR_CODES.TENANT_SUSPENDED,
]);

const NOT_FOUND_CODES = new Set<string>([ERROR_CODES.NOT_FOUND]);

const SERVER_CODES = new Set<string>([
  ERROR_CODES.INTERNAL_SERVER_ERROR,
  ERROR_CODES.AI_EVALUATION_FAILED,
  ERROR_CODES.AI_PAYMENT_REQUIRED,
  ERROR_CODES.STORAGE_ERROR,
  ERROR_CODES.EMAIL_FAILED,
]);

const BUSINESS_CODES = new Set<string>([
  ERROR_CODES.CONFLICT,
  ERROR_CODES.EMAIL_ALREADY_IN_USE,
  ERROR_CODES.JOB_NOT_OPEN,
  ERROR_CODES.JOB_IS_CLOSED,
  ERROR_CODES.INVALID_STAGE_TRANSITION,
  ERROR_CODES.ALREADY_IN_PIPELINE,
  ERROR_CODES.NO_RESUME,
  ERROR_CODES.NO_SKILL_WEIGHTS,
  ERROR_CODES.LINKEDIN_NOT_CONNECTED,
  ERROR_CODES.LINKEDIN_TOKEN_EXPIRED,
  ERROR_CODES.LINKEDIN_POST_FAILED,
  ERROR_CODES.LINKEDIN_ORG_NOT_FOUND,
  ERROR_CODES.LINKEDIN_RATE_LIMITED,
  ERROR_CODES.LINKEDIN_DUPLICATE_POST,
  ERROR_CODES.LINKEDIN_SCOPE_DENIED,
  ERROR_CODES.LINKEDIN_OAUTH_FAILED,
  ERROR_CODES.LINKEDIN_NETWORK_ERROR,
]);

export function getErrorCategory(errorCode: string, statusCode: number): ErrorCategory {
  if (errorCode === ERROR_CODES.NETWORK_ERROR) return ERROR_CATEGORIES.NETWORK;
  if (VALIDATION_CODES.has(errorCode)) return ERROR_CATEGORIES.VALIDATION;
  if (AUTH_CODES.has(errorCode)) return ERROR_CATEGORIES.AUTH;
  if (PERMISSION_CODES.has(errorCode)) return ERROR_CATEGORIES.PERMISSION;
  if (NOT_FOUND_CODES.has(errorCode)) return ERROR_CATEGORIES.NOT_FOUND;
  if (SERVER_CODES.has(errorCode)) return ERROR_CATEGORIES.SERVER;
  if (BUSINESS_CODES.has(errorCode)) return ERROR_CATEGORIES.BUSINESS;

  if (statusCode === 0) return ERROR_CATEGORIES.NETWORK;
  if (statusCode === 401) return ERROR_CATEGORIES.AUTH;
  if (statusCode === 403) return ERROR_CATEGORIES.PERMISSION;
  if (statusCode === 404) return ERROR_CATEGORIES.NOT_FOUND;
  if (statusCode >= 500) return ERROR_CATEGORIES.SERVER;
  if (statusCode >= 400) return ERROR_CATEGORIES.VALIDATION;

  return ERROR_CATEGORIES.SERVER;
}

export function toastVariantForCategory(category: ErrorCategory): 'destructive' | 'warning' {
  if (category === ERROR_CATEGORIES.VALIDATION) return 'warning';
  if (category === ERROR_CATEGORIES.BUSINESS) return 'warning';
  return 'destructive';
}
